### ISSUE TITLE
feat: on mobile browser the address bar does not hide

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-v1#22]
_From @awebdeveloper on December 11, 2015 3:3_

**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On mobile browser the address bar does not hide. This is coz ionic fills up the available space and the way these browsers work is if u scroll down it will hide the address bar</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4756_

**Comment by jgw96** [comment]
_From @mlynch on December 15, 2015 2:58_

I don't think there's much we can do to avoid this. An Ionic app looks and feels like an app, and takes up the available viewport space. 

Unless I'm wrong and there's an alternative here?

**Comment by jgw96** [comment]
_From @mlynch on December 15, 2015 16:27_

Reopening because I think this is something we could do on mobile web

**Comment by jgw96** [comment]
_From @awebdeveloper on December 17, 2015 2:17_

Good. When do you think someone will be able to look into this

**Comment by jgw96** [comment]
_From @denyo on January 13, 2016 17:5_

It is possible to achieve this but it is going to get ugly when navigating between parent/child views which slide in from the side.

To achieve this the positioning model (`position: block; top: 0; left: 0; right 0; bottom: 0;`) needs to go away so that the content is naturally scrolled on the body node. The nav bar would be `position: fixed; top: 0; left: 0; right:0; height: 44px;` and the main content would be `padding: 44px 0 0;`. So far so good. 

The trouble starts when you switch between views. This is due to their different heights. To better understand this, imagine you have a long list of items and a details page which live in two separate views. Now you scroll down the list of items a bit and the height of your mobile browser increases because the address bar and/or navigation buttons disappear. Next you click one of the list items and transition into the details page which is right next to the list. What has to happen here besides the transition is the body (with natural scrolling) needs to jump back to the top so that you see the beginning of the details page as expected. Afterwards the height of the body needs to be adjusted to fit the actual content so that scrollbars work correctly. Now you are at the very top now and most likely you got your address bar back.

**Comment by jgw96** [comment]
_From @derwu on March 7, 2016 20:21_

If anyone is solved? I solved this partially like @denyo but with the same problem. When you use ionic as webapp is necessary to solve this.

**Comment by jgw96** [comment]
_From @awebdeveloper on March 8, 2016 12:53_

@denyo  i don't get what u say

**Comment by jgw96** [comment]
_From @denyo on March 8, 2016 14:47_

You could also try this library although it requires you to swipe that initial overlay/modal to go into fullscreen: https://github.com/gajus/brim

**Comment by jgw96** [comment]
_From @jiazhengshi on July 27, 2016 18:37_

Any update on this feature request?

**Comment by patrickmcd** [comment]
I don't think this feature request is limited to only V1.

**Comment by jgw96** [comment]
Hello all! Since we are not planning on adding any new features to Ionic 1 I am going to close this issue for now. This is something that we are planning on looking at in Ionic 2 once it hits stable (should be very very very soon (: ). Thanks everyone for using Ionic!
